config/routes.rb
GitlabIssuesUploader::Application.routes.draw do
  root :to => "projects#index"
  match 'projects/update' => 'projects#update'

  match 'issues' => 'issues#index', :as=> :issues
  match ':id/browse_issues' => 'issues#browse', :as=> :browse_issues_id
  match 'browse' => 'issues#browse', :as=> :browse_issues
  match 'import' => 'issues#import', :as=> :import_issues
  match 'export' => 'issues#export', :as=> :export_issues
  match 'download' => 'issues#download', :as=> :download_issues

end

app/models/issue.rb
class Issue < ActiveRecord::Base

  # Assosiate the Issue model with Project model.
  belongs_to :project

  # Attribute accessors.
  attr_accessible :gitlab_id, :status, :tc_id, :title, :milestone, :tags

  # Validations.
  validates :gitlab_id, uniqueness: true, presence: true
  validates :tc_id, uniqueness: true, presence: true
  validates :status, presence: true
  validates :title, presence: true

  # Model method will convert the issue data to the csv format.
  #
  # issues = Array of all the issues matching the user requirement.
  #
  # all_projects_selcted = A boolean to print the project name in the csv.
  #
  # Examples
  #   Issue.to_csv(issues,true)
  #
  # Returns the csv file with the issue data.
  def self.to_csv(issues,all_projects_selected)
    column_names = {"TC ID"=>"tc_id","GitLab ID"=>"gitlab_id","Title"=>"title","Status"=>"status","Milesonte" =>"milestone","Tags"=>"tags"}
    column_names["Project Name"]="" if all_projects_selected == true
    column_ids = column_names.values
    CSV.generate do |csv|
      csv << column_names.keys
      issues.each do |issue|
        data_items = issue.attributes.values_at(*column_ids)
        if all_projects_selected == true
          data_items.pop
          data_items.push(Project.find(issue.project_id).name)
        end
        csv << data_items
      end
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base

  # Attribute accessors.
  attr_accessible :gitlab_id, :name

  # Assosiate the Project model with Issue model.
  has_many :issues, :dependent => :destroy

  # Validations
  validates :gitlab_id, uniqueness: true, presence: true
  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  include IssuesHelper
  # Controller method will invoke the corresponding view page(index.html.erb)
  #
  #
  # Examples
  #   index
  #
  # Invoke the index.html.erb page.
  def index
  end
  # Controller method will get the response from the users project selection (
  # through index.html.erb page), and will redirect the user to the browse page
  # (browse.html.erb)
  #
  # params[:id] = Project id in case of project id passed in the url.
  # params[:user_pick] = Project id in case project id passed through the form.
  #
  # Examples
  #   browse
  #
  # Redirect the project id to the browse.html.erb page.
  def browse
    if params[:id]==nil && params[:user_pick] ==nil
      flash[:error] = "Pick any project to continue.."
      redirect_to root_path
      return
    end
    @project_id = params[:id]||params[:user_pick][:project]
  end
  # Controller method will get the csv file from the browse page, and will use
  # the same to create the issues in gitlab and in local database. After the
  # successfull creation of the records user will be redirected to the browse
  # page (browse.html.erb).
  #
  # params[:file_upload][:file] = CSV file with the Gitlab issues.
  #
  # Examples
  #   import
  #
  # Redirect the user to the browse page (browse.html.erb) with the appropriate
  # status messages.
  def import
    if params[:file_upload][:file] == nil
     flash[:error] = "You can't proceed with out file selection."
     redirect_to :controller => 'issues', :action => 'browse', :id => params[:file_upload][:project_id]
     return
    else
      csv_file = params[:file_upload][:file].tempfile
      csv_data = CSV.read(csv_file)
      project_id = params[:file_upload][:project_id]
      csv_data.shift
      csv_data.each do |row|
        tc_id = row[0]
        status = row[9]
        title = row[1]
        component = row[4]
        priority = row[2]
        severity = row[3]
        # Used to maintain the uniqueness of issues.
        if Issue.find_by_tc_id(row[0])!=nil
          flash[:notice] = "Duplicated Entry for : #{row[0]}. Last updated issue is #{Issue.last.tc_id}."
          next
        end
        Delayed::Job.enqueue(UploadJob.new(row,project_id))
        # Update the issue at gitlab only if the issue id (tc_id) is unique.
        #new_issue = $Gitlab_client.create_issue(project_id,row[1],{:description=>prepare_issue_body(row),:labels=>["import",status,component,priority,severity]})
        #project = Project.find_by_gitlab_id(project_id)
        # After the update at gitlab, now update the same at the local db.
        #project.issues.create(:gitlab_id=>new_issue.id,:title=>title,:tc_id=>tc_id,:status=>status)
      end
      flash[:notice] = "All the issues will be uploaded shortely."
      redirect_to :controller => 'issues', :action => 'browse', :id => project_id
    end
  end
  # Controller method will invoke the corresponding view page (export.html.
  # erb).
  #
  #
  # Examples
  #   export
  #
  # Redirect the user to the export.html.erb page.
  def export
  end
  # Controller method will get the response from the users project selection
  # (through export.html.erb page), and will export the issues to the csv file.
  #
  # params[:user_pick] = Project id captured from the export.html.erb page.
  #
  # Examples
  #   download
  #
  # Renders a csv file with the issues.
  def download
    user_query_passed = false
    all_projects = false
    user_query_passed = true if params[:user_pick] != nil
    all_projects = true if user_query_passed == true && params[:user_pick][:project]=="all"
    @issues = Issue.order(:created_at)
    @issues = Project.find_by_gitlab_id(params[:user_pick][:project]).issues.order(:created_at) if user_query_passed == true && all_projects == false
    render :text=>Issue.to_csv(@issues,all_projects)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ProjectsHelper
  # Controller method will invoke the corresponding view page(index.html.erb).
  #
  #
  # Examples
  #   index
  #
  # Redirect the user to the index.html.erb page with the project list.
  def index
    # Update the project list from the gitlab, if there exists no projects in the list.
    load_from_gitlab if Project.count == 0
    @projects = Project.all
  end
  # Controller method will update the records from the gitlab and
  # will redirect the user to the root page.
  #
  #
  # Examples
  #   update
  #
  # Redirect the user to the root page.
  def update
    load_from_gitlab
    flash["notice"] = "Project List updated successfully."
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  # Helper method will get the project list from the gitlab api.
  #
  # Examples
  #   load_from_gitlab
  #
  # Returns the project list.
  def load_from_gitlab
    @projects = $Gitlab_client.projects
    projects_local_db = Project.pluck(:gitlab_id)
    @projects.each do |project|
      projects_local_db = projects_local_db - [project.id]
      if Project.find_by_gitlab_id(project.id) == nil
        Project.create(:gitlab_id=>project.id, :name=>project.name)
      end
    end
    projects_local_db.each do |id|
      project = Project.find_by_gitlab_id(id)
      project.destroy
    end
  end
end

app/views/issues/browse.html.erb
<div class="span6 well">
  <%= form_for :file_upload, :url=>import_issues_path, :multipart=>true do |f| %>
  <legend>
    Pick the file
    <hr>
  </legend>
  <%= f.hidden_field :project_id, :value => @project_id%>
  <%= f.file_field :file, style:"visibility:hidden", id:"csvfile"%>
  <div class="input-append">
    <%= f.text_field :text, class:"input-xlarge", id:"subfile"%>
    <a class="input-small btn btn-info" onclick="$('#csvfile').click();">Browse</a>
  </div>
  <br>
  <%= f.submit :Upload, class:"input-medium btn btn-info"%>
  <% end %>
</div>

app/views/issues/export.html.erb
  <div class="span6 well">
    <legend>
      Pick the Project
      <hr>
    </legend>
    <%= form_for :user_pick ,:url=>download_issues_path(format: "csv") do |f| %>
    <div class="input-append">
      <% options = Project.all.collect{|p|[p.name,p.gitlab_id]}%>
      <% options.unshift(["All","all"])%>
      <%= f.select :project, options, class:"selectpicker"%>
      <%= f.submit :Download, class:"input-small btn btn-info"%>
    </div>
    <% end %>
  </div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<div class="alert alert-<%= name.to_s == "notice" ? "success" : "error" %>">
  <a class="close" data-dismiss="alert">&times;</a>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse collapse">
        <div class="navbar navbar-fixed-top">
          <nav class="navbar-inner">
            <a class='brand' href="/">GitLab Issues Uploader</a>
            <ul class="nav">
              <%= render 'layouts/navigation_links' %>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'Import', root_path %></li>
<li><%= link_to 'Export', export_issues_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Gitlab Issues Uploader" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Gitlab Issues Uploader" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%# application layout styled for Bootstrap 2.3 %>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/projects/index.html.erb
  <div class="span6 well">
    <legend>
      Pick the Project
      <hr>
    </legend>
    <%= form_for :user_pick ,:url=>browse_issues_path do |f| %>
    <div class="input-append">
      <%= f.select :project, Project.all.collect{|p|[p.name,p.gitlab_id]}%>
      <%= f.submit :Next, class:"input-medium btn btn-info"%>
    </div>
    <% end %>
  </div>
  <div class="span6 well">
    <legend>
      (or) Update the Project List
    </legend>
      <%= link_to "Update", projects_update_path, class:"input-medium btn btn-info"%>
   </div>